import { Head } from "@inertiajs/react"
import SurveyPreview from "@/components/survey-builder/survey-preview"

interface PublicViewProps {
  survey: {
    id: number;
    title: string;
    slug: string;
    structure: any[];
  }
}

export default function PublicView({ survey }: PublicViewProps) {
  // Calculate total pages from the blocks
  const totalPages = Math.max(...survey.structure.map(b => b.page || 1), 1);

  return (
    <div className="min-h-screen bg-[#09090b] text-slate-50 selection:bg-indigo-500/30">
      <Head title={survey.title} />

      {/* Ambient Background Glows */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-[10%] -left-[10%] w-[40%] h-[40%] bg-indigo-500/10 blur-[120px] rounded-full" />
        <div className="absolute top-[60%] -right-[10%] w-[30%] h-[30%] bg-purple-500/10 blur-[120px] rounded-full" />
      </div>

      <div className="relative z-10 max-w-2xl mx-auto px-6 py-16 md:py-24">
        {/* Header Section */}
        <div className="mb-12 space-y-4">
          <div className="flex items-center justify-center space-x-2">
            <div className="h-[1px] w-8 bg-gradient-to-r from-transparent to-indigo-500" />
            <span className="text-[10px] font-black uppercase tracking-[0.3em] text-indigo-400">
              Official Survey
            </span>
            <div className="h-[1px] w-8 bg-gradient-to-l from-transparent to-indigo-500" />
          </div>

          <h1 className="text-4xl md:text-5xl font-bold text-center tracking-tight bg-clip-text text-transparent bg-gradient-to-b from-white to-slate-400">
            {survey.title}
          </h1>
        </div>

        {/* Survey Card Container */}
        <div className="relative group">
          {/* Border Gradient Effect */}
          <div className="absolute -inset-[1px] bg-gradient-to-b from-slate-700 to-slate-800 rounded-[2.5rem] opacity-50" />

          {/* Main Content Box */}
          <div className="relative bg-[#0c0c0e] border border-white/5 shadow-2xl rounded-[2.5rem] p-8 md:p-12 backdrop-blur-sm">
            <SurveyPreview
              blocks={survey.structure}
              totalPages={totalPages}
              isPublic={true}
              surveySlug={survey.slug}
            />
          </div>
        </div>

        {/* Footer */}
        <footer className="mt-16 flex flex-col items-center justify-center space-y-6">
          <div className="flex items-center space-x-4 opacity-30 hover:opacity-100 transition-opacity">
            <div className="h-px w-12 bg-slate-700" />
            <span className="text-[10px] font-bold uppercase tracking-widest italic">
              Generated by Gemini Survey
            </span>
            <div className="h-px w-12 bg-slate-700" />
          </div>
        </footer>
      </div>
    </div>
  )
}